#line 1 "lex.yy.cpp"
    #include <stdint.h>

#line 4 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[412] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      136,  134,  132,  133,  133,  117,  134,   74,  134,  109,
       91,   92,   72,   70,   99,   71,   88,   73,  105,  105,
       90,  100,   77,   75,   79,   69,   93,   94,   68,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   97,
      101,   98,  114,  116,  116,  117,  115,  115,  119,  118,
      131,  125,  126,  126,  124,  131,  122,  123,   85,   86,
      132,  133,  120,   82,  109,  108,  109,  111,   87,   89,
      110,  104,  105,  107,  107,  107,  103,  105,  107,  107,

      107,  107,  105,   84,   81,   78,   76,   80,   69,   95,
       69,   69,    3,   69,   69,   69,   69,   10,   69,   69,
       69,   69,   69,   69,   69,   69,   25,   26,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   40,   69,   42,
       69,   69,   69,   69,   69,   69,   69,   53,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   96,   83,  114,
      116,  112,  113,  119,  130,  127,  127,  128,  125,  126,
      129,  121,  109,    0,  110,  102,  104,  106,  106,  103,
      105,    0,  104,  105,  105,   69,    2,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   16,   69,   69,

       69,   69,   69,   21,   22,   69,   69,   69,   69,   69,
       32,   69,   69,   69,   69,   69,   38,   69,   69,   69,
       69,   69,   46,   69,   69,   69,   69,   69,   69,   54,
       69,   69,   57,   59,   69,   69,   69,   69,   69,  127,
        0,  104,  106,  106,    0,  104,  106,  105,  107,  104,
      104,  106,  103,  106,  105,  107,  105,  107,   69,   69,
        5,   69,   69,   69,   69,   11,   69,   14,   15,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   31,
       69,   69,   69,   69,   69,   39,   41,   69,   69,   69,
       69,   69,   69,   69,   52,   66,   55,   69,   58,   60,

       61,   69,   63,   69,  104,  104,  104,  103,  106,  104,
      106,  106,  106,  104,   69,   69,    6,    7,   69,   69,
       69,   69,   69,   69,   67,   69,   20,   69,   69,   69,
       69,   69,   33,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   62,   64,  106,  106,  104,
      106,  104,  103,  106,   69,    4,   69,   69,   69,   13,
       69,   18,   69,   69,   24,   69,   28,   69,   69,   34,
       35,   69,   69,   69,   69,   45,   47,   49,   50,   51,
       56,   65,  106,   69,    8,   69,   69,   69,   19,   69,
       27,   69,   69,   36,   69,   69,   44,   48,    1,    9,

       12,   69,   23,   69,   30,   69,   43,   17,   29,   37,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    1,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,    1,    1,   29,   30,   29,   29,   31,   32,
       33,   33,   34,   33,   33,   35,   36,   33,   37,   33,
       33,   33,   33,   33,   38,   33,   33,   39,   33,   33,
       40,   41,   42,    1,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   33,   53,   54,   55,
       56,   57,   33,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,    1,    1,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    2,    1,    3,    1,    1,    1,
        4,    5,    1,    5,    1,    1,    1,    6,    1,    7,
        7,    7,    7,    1,    1,    1,    1,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    1,
        8,    1,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    9,    1,    9,   10
    } ;

static const flex_int16_t yy_base[431] =
    {   0,
        0,    0,   68,   69,   70,   71,   81,   82,   23,   24,
      846,  847,   92,  847,  842,  847,  837,  847,  833,   68,
      828,  847,  847,  847,  847,  813,  822,  820,  134,   65,
      814,  847,   80,  847,  810,    0,  768,  847,    0,   58,
       57,  782,   50,   61,   74,  781,   78,   71,   76,   92,
       85,   70,  785,   98,  150,   82,  118,   48,  780,  847,
      134,  847,    0,  847,  828,  847,  816,  816,    0,  847,
      200,    0,  847,  825,  847,  209,  760,  757,  847,  847,
      157,  847,  847,  847,  134,  847,  206,  847,  847,  847,
        0,  254,  188,    0,  189,  209,    0,    0,  201,  790,

      289,  214,  228,  847,  847,  847,  847,  847,    0,  847,
      765,  776,  763,  762,  770,  775,  189,  185,  187,  771,
      197,  764,  164,  758,  760,  758,    0,  198,  747,  752,
      751,  756,  762,  748,  753,  743,  752,    0,  755,    0,
      754,  748,  754,  199,  743,  209,  747,    0,  217,  736,
      746,  741,  735,  733,  232,  724,  734,  847,  847,    0,
      847,  847,  847,    0,  847,  779,  286,  847,    0,  847,
      847,  847,  767,  254,    0,  847,  321,    0,  277,  293,
      356,  302,  364,  285,  415,  717,    0,  727,  726,  712,
      702,  716,  701,  691,  681,  686,  682,    0,  681,  667,

      651,  658,  652,    0,  653,  651,  647,  641,  644,  617,
        0,  603,  603,  586,  602,  597,    0,  591,  588,  584,
      579,  587,    0,  578,  590,  577,  574,  579,  585,    0,
      584,  586,  623,    0,  581,  572,  573,  574,  571,  621,
      319,    0,  325,    0,  345,  445,    0,    0,  311,  381,
      453,  259,  420,  428,  329,  334,    0,  504,  564,  563,
        0,  565,  560,  557,  567,    0,  313,    0,    0,  559,
      556,  565,  559,  564,  549,  564,  549,  551,  547,    0,
      548,  550,  541,  547,  526,    0,    0,  522,  535,  513,
      506,  513,  506,  510,    0,    0,    0,  488,  847,    0,

        0,  494,    0,  475,  449,  489,    0,  405,  432,  523,
      483,  350,  352,  561,  477,  459,    0,    0,  465,  473,
      464,  445,  440,  440,    0,  440,    0,  439,  434,  434,
      436,   89,    0,  425,  434,  426,  421,  405,  373,  386,
      375,  363,  373,  354,  350,    0,  402,  540,  493,  547,
      508,  553,  566,  580,  360,    0,  345,  338,  338,    0,
      343,    0,  328,  336,    0,  329,    0,  344,  339,    0,
        0,  334,  336,  331,  323,    0,  356,    0,    0,    0,
        0,  847,  518,  298,    0,  292,  267,  261,    0,  246,
        0,  250,  238,    0,  233,  225,    0,  847,    0,    0,

        0,  201,    0,  206,    0,  156,    0,    0,    0,    0,
      847,  650,  660,  670,  680,  687,  697,  707,  717,  727,
      737,  747,  752,  153,  762,  769,  776,  780,  787,  794
    } ;

static const flex_int16_t yy_def[431] =
    {   0,
      411,    1,  412,  412,  413,  413,  414,  414,    1,    1,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  415,
      411,  411,  411,  411,  411,  411,  411,  411,  411,   29,
      411,  411,  411,  411,  411,  416,  411,  411,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  411,
      411,  411,  417,  411,  411,  411,  411,  411,  418,  411,
      419,  420,  411,  411,  411,  419,  411,  411,  411,  411,
      411,  411,  411,  411,  415,  411,  421,  411,  411,  411,
      422,  423,   29,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  411,  411,  411,  411,  411,  416,  411,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  411,  411,  417,
      411,  411,  411,  418,  411,  411,  411,  411,  420,  411,
      411,  411,  421,  425,  422,  411,  423,  426,  426,  427,
      424,  411,  428,  181,  181,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  411,
      411,  177,  426,  426,  411,  427,  426,  181,  424,  177,
      428,  429,  430,  429,  181,  424,  185,  424,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  411,  416,

      416,  416,  416,  416,  246,  177,  246,  427,  426,  177,
      426,  429,  429,  430,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  426,  426,  177,
      426,  246,  430,  429,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  411,  426,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  411,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
        0,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411
    } ;

static const flex_int16_t yy_nxt[918] =
    {   0,
       12,   13,   14,   13,   15,   12,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   30,   30,   31,   32,   33,   34,   35,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   37,
       12,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       36,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   36,   59,   36,   60,   61,   62,   36,
       64,   64,   65,   65,   66,   66,   70,   70,   86,   67,
       67,   68,   68,   73,   73,   74,   74,   75,   75,   79,
       79,   80,   80,   81,   94,   81,  105,  117,  155,  156,

      114,   94,  111,   94,  115,  118,  106,  107,   87,   94,
       71,   71,  112,  119,  129,  120,  113,  122,  130,  131,
       94,   76,   76,  132,  121,  123,  127,  142,   94,  124,
      143,  133,  128,  138,  125,  135,  134,  368,  151,  136,
      152,  139,  140,  369,   86,  145,  141,   77,   77,   78,
       78,   92,  137,   93,   93,   93,   93,  146,   81,   94,
       81,  153,   94,   95,   96,   97,   94,   98,   98,   97,
       99,  100,  101,  154,   87,  158,  102,   94,   95,   94,
       94,   96,   97,   94,   94,   94,   98,   97,   98,   99,
       94,   94,   98,   94,  103,   94,   94,  101,   98,   94,

      147,  159,  166,  410,  167,  148,  168,  149,  181,  181,
      168,  166,   85,  167,  150,  171,  174,   94,  202,  171,
      184,  184,  184,  182,   94,  182,   94,  203,  183,  183,
      183,  183,   94,   93,   93,   93,   93,  192,  196,  194,
      168,  193,  199,   94,  223,  197,   85,  195,  207,  171,
      208,   94,  226,  409,  168,  408,  200,  209,  224,  168,
       85,  168,   98,  171,   86,   85,  227,   85,  171,  244,
      171,  176,  407,  177,  177,  177,  177,  229,  406,  236,
       98,  230,   98,  237,  179,  180,   98,  240,  166,  180,
      405,  245,   98,  245,  241,  404,  246,  246,  246,  246,

      403,  179,  180,  244,  255,  255,  255,  180,  185,  185,
      185,  185,  244,  244,  244,  244,  402,  185,  185,  185,
      185,  250,  250,  250,  250,  174,  401,  256,  244,  174,
      248,  248,  185,  185,  185,  185,  185,  185,  411,  400,
      242,  242,  242,  242,  305,  305,  305,  305,  255,  255,
      255,  179,  180,  255,  255,  255,  180,  399,  321,  174,
      244,  398,  244,  243,  306,  306,  306,  306,  179,  180,
      397,  256,  322,  174,  180,  248,  248,  396,  174,  395,
      174,  394,  393,  251,  251,  251,  251,  392,  391,   98,
       98,  390,  389,  100,  388,  253,  387,  386,  249,  253,

      310,  310,  310,  310,  385,  384,  254,  382,   98,  381,
       98,  178,  253,  380,   98,  244,  103,  253,  379,  244,
       98,  244,  378,  311,  244,  244,  244,  244,  178,  377,
      244,  376,  375,  178,  257,  257,  257,  257,  244,  312,
      312,  312,  312,  257,  257,  257,  257,  314,  314,  314,
      314,  307,  307,  307,  307,  244,  374,  258,  257,  257,
      257,  257,  257,  257,  307,  307,  307,  307,  305,  305,
      305,  305,  251,  251,  251,  251,  308,  373,  372,  348,
      308,  371,  370,  367,  253,  366,  365,  309,  253,  247,
      364,  349,  363,  308,  362,  254,  348,  244,  308,  361,

      360,  253,  352,  352,  352,  352,  253,  359,  350,  350,
      350,  350,  305,  305,  305,  305,  358,  357,  356,  178,
      355,  347,  178,  257,  257,  257,  257,  307,  307,  307,
      307,  351,  257,  257,  257,  257,  178,  352,  352,  352,
      352,  346,  310,  310,  310,  310,  345,  257,  257,  257,
      257,  257,  257,  178,  245,  344,  245,  343,  342,  246,
      246,  246,  246,  341,  340,  311,  350,  350,  350,  350,
      178,  244,  352,  352,  352,  352,  244,  178,  339,  338,
      314,  314,  314,  314,  337,  312,  312,  312,  312,  351,
      244,  336,  353,  335,  178,  383,  353,  334,  333,  314,

      314,  314,  314,  354,  332,  331,  330,  329,  328,  353,
      327,  326,  325,  324,  353,  323,  320,  319,  318,  317,
      316,  315,  240,  304,  303,  302,  301,  300,  299,  298,
      247,  297,  296,  295,  294,  247,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  244,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       85,  280,   85,   85,   85,   85,   85,   85,   85,   85,
      109,  279,  278,  109,  277,  276,  109,  160,  275,  274,

      160,  273,  160,  160,  160,  160,  160,  164,  164,  272,
      164,  164,  164,  164,  271,  164,  164,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  169,  270,  269,
      169,  169,  169,  169,  268,  267,  169,  173,  266,  173,
      173,  173,  173,  173,  173,  173,  173,  175,  265,  175,
      175,  175,  175,  175,  175,  175,  175,  178,  178,  264,
      263,  178,  174,  262,  174,  174,  174,  174,  174,  174,
      174,  174,  244,  261,  260,  244,  259,  411,  244,  247,
      240,  239,  247,  238,  235,  247,  252,  234,  233,  252,
      312,  232,  231,  312,  228,  225,  312,  313,  222,  221,

      313,  220,  219,  313,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  206,  205,  204,  201,  198,  191,  190,
      189,  188,  187,  186,   98,  172,  172,  170,  163,  162,
      161,  157,  144,  126,  116,  110,  108,  104,   91,   90,
       89,   88,   84,   83,   82,  411,   11,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411
    } ;

static const flex_int16_t yy_chk[918] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    3,    4,    5,    6,   20,    3,
        4,    3,    4,    7,    8,    7,    8,    7,    8,    9,
       10,    9,   10,   13,   30,   13,   33,   43,   58,   58,

       41,   30,   40,   30,   41,   43,   33,   33,   20,   30,
        5,    6,   40,   44,   48,   44,   40,   45,   48,   49,
       30,    7,    8,   49,   44,   45,   47,   52,   30,   45,
       52,   49,   47,   51,   45,   50,   49,  332,   56,   50,
       56,   51,   51,  332,   85,   54,   51,    7,    8,    7,
        8,   29,   50,   29,   29,   29,   29,   54,   81,  424,
       81,   57,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   57,   85,   61,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       55,   61,   71,  406,   71,   55,   71,   55,   95,   95,
       71,   76,   87,   76,   55,   76,   87,   93,  123,   76,
       99,   99,   99,   96,   93,   96,   93,  123,   96,   96,
       96,   96,   93,  102,  102,  102,  102,  117,  119,  118,
       71,  117,  121,   93,  144,  119,   87,  118,  128,   76,
      128,   93,  146,  404,   71,  402,  121,  128,  144,   71,
       87,   71,  103,   76,  174,   87,  146,   87,   76,  252,
       76,   92,  396,   92,   92,   92,   92,  149,  395,  155,
      103,  149,  103,  155,   92,   92,  103,  167,  167,   92,
      393,  179,  103,  179,  174,  392,  179,  179,  179,  179,

      390,   92,   92,  180,  184,  184,  184,   92,  101,  101,
      101,  101,  180,  180,  180,  180,  388,  101,  101,  101,
      101,  182,  182,  182,  182,  241,  387,  184,  252,  241,
      249,  249,  101,  101,  101,  101,  101,  101,  177,  386,
      177,  177,  177,  177,  243,  243,  243,  243,  255,  255,
      255,  177,  177,  256,  256,  256,  177,  384,  267,  241,
      312,  377,  313,  177,  245,  245,  245,  245,  177,  177,
      375,  255,  267,  241,  177,  181,  181,  374,  241,  373,
      241,  372,  369,  183,  183,  183,  183,  368,  366,  181,
      181,  364,  363,  181,  361,  183,  359,  358,  181,  183,

      250,  250,  250,  250,  357,  355,  183,  347,  181,  345,
      181,  250,  183,  344,  181,  308,  181,  183,  343,  312,
      181,  313,  342,  250,  308,  308,  308,  308,  250,  341,
      253,  340,  339,  183,  185,  185,  185,  185,  254,  253,
      253,  253,  253,  185,  185,  185,  185,  254,  254,  254,
      254,  309,  309,  309,  309,  246,  338,  185,  185,  185,
      185,  185,  185,  185,  246,  246,  246,  246,  305,  305,
      305,  305,  251,  251,  251,  251,  246,  337,  336,  305,
      246,  335,  334,  331,  251,  330,  329,  246,  251,  253,
      328,  305,  326,  246,  324,  251,  305,  254,  246,  323,

      322,  251,  311,  311,  311,  311,  251,  321,  306,  306,
      306,  306,  349,  349,  349,  349,  320,  319,  316,  306,
      315,  304,  251,  258,  258,  258,  258,  351,  351,  351,
      351,  306,  258,  258,  258,  258,  306,  383,  383,  383,
      383,  302,  310,  310,  310,  310,  298,  258,  258,  258,
      258,  258,  258,  310,  348,  294,  348,  293,  292,  348,
      348,  348,  348,  291,  290,  310,  350,  350,  350,  350,
      310,  314,  352,  352,  352,  352,  353,  350,  289,  288,
      314,  314,  314,  314,  285,  353,  353,  353,  353,  350,
      354,  284,  314,  283,  350,  352,  314,  282,  281,  354,

      354,  354,  354,  314,  279,  278,  277,  276,  275,  314,
      274,  273,  272,  271,  314,  270,  265,  264,  263,  262,
      260,  259,  240,  239,  238,  237,  236,  235,  233,  232,
      314,  231,  229,  228,  227,  353,  226,  225,  224,  222,
      221,  220,  219,  218,  216,  215,  214,  213,  212,  354,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      415,  210,  415,  415,  415,  415,  415,  415,  415,  415,
      416,  209,  208,  416,  207,  206,  416,  417,  205,  203,

      417,  202,  417,  417,  417,  417,  417,  418,  418,  201,
      418,  418,  418,  418,  200,  418,  418,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  420,  199,  197,
      420,  420,  420,  420,  196,  195,  420,  421,  194,  421,
      421,  421,  421,  421,  421,  421,  421,  422,  193,  422,
      422,  422,  422,  422,  422,  422,  422,  423,  423,  192,
      191,  423,  425,  190,  425,  425,  425,  425,  425,  425,
      425,  425,  426,  189,  188,  426,  186,  173,  426,  427,
      166,  157,  427,  156,  154,  427,  428,  153,  152,  428,
      429,  151,  150,  429,  147,  145,  429,  430,  143,  142,

      430,  141,  139,  430,  137,  136,  135,  134,  133,  132,
      131,  130,  129,  126,  125,  124,  122,  120,  116,  115,
      114,  113,  112,  111,  100,   78,   77,   74,   68,   67,
       65,   59,   53,   46,   42,   37,   35,   31,   28,   27,
       26,   21,   19,   17,   15,   11,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fsharp_lexer.l"
#define YY_NO_UNISTD_H 1





#line 32 "fsharp_lexer.l"
    #define YY_NO_UNISTD_H

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <errno.h>
    #include <string>
    #include <vector>
    #include <iostream>
    #include <icu.h>

    #pragma comment(lib, "icu.lib")

    /* ----- прототипы функций ----- */

    void strip_underscores(const char* src, char* out, size_t cap);
    void convert_to_decimal(const char* src, int base);
    void convert_to_float(const char* src);
    void parse_unicode(std::string& buf, long cp);
    void parse_string_escape(std::string& buf, char c);
    void parse_template_escape(char c);

    bool hadError = false;
#line 848 "lex.yy.cpp"
#line 849 "lex.yy.cpp"

#define INITIAL 0
#define MULTILINE_COMMENT 1
#define STRING 2
#define INTERPOLATED_STRING 3
#define INTERPOLATION_EXPR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 57 "fsharp_lexer.l"



#line 61 "fsharp_lexer.l"
    /* ----- комментарии и строковые литералы ----- */

    int commentDepth = 0;
    std::string stringBuffer;

    /* ----- фигурные скобки внутри интерполированных строк ----- */

    std::vector<int> braceStack;


    /* ----- ключевые слова ----- */

#line 1097 "lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 412 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 411 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "fsharp_lexer.l"
{ printf("KW_ABSTRACT: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "fsharp_lexer.l"
{ printf("KW_AND: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "fsharp_lexer.l"
{ printf("KW_AS: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "fsharp_lexer.l"
{ printf("KW_ASSERT: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "fsharp_lexer.l"
{ printf("KW_BASE: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "fsharp_lexer.l"
{ printf("KW_BEGIN: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "fsharp_lexer.l"
{ printf("KW_CLASS: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "fsharp_lexer.l"
{ printf("KW_DEFAULT: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "fsharp_lexer.l"
{ printf("KW_DELEGATE: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "fsharp_lexer.l"
{ printf("KW_DO: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "fsharp_lexer.l"
{ printf("KW_DONE: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "fsharp_lexer.l"
{ printf("KW_DOWNCAST: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "fsharp_lexer.l"
{ printf("KW_DOWNTO: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "fsharp_lexer.l"
{ printf("KW_ELIF: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "fsharp_lexer.l"
{ printf("KW_ELSE: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "fsharp_lexer.l"
{ printf("KW_END: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "fsharp_lexer.l"
{ printf("KW_EXCEPTION: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "fsharp_lexer.l"
{ printf("KW_EXTERN: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "fsharp_lexer.l"
{ printf("KW_FINALLY: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "fsharp_lexer.l"
{ printf("KW_FIXED: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "fsharp_lexer.l"
{ printf("KW_FOR: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "fsharp_lexer.l"
{ printf("KW_FUN: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "fsharp_lexer.l"
{ printf("KW_FUNCTION: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 "fsharp_lexer.l"
{ printf("KW_GLOBAL: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 97 "fsharp_lexer.l"
{ printf("KW_IF: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 98 "fsharp_lexer.l"
{ printf("KW_IN: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "fsharp_lexer.l"
{ printf("KW_INHERIT: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 100 "fsharp_lexer.l"
{ printf("KW_INLINE: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 101 "fsharp_lexer.l"
{ printf("KW_INTERFACE: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "fsharp_lexer.l"
{ printf("KW_INTERNAL: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "fsharp_lexer.l"
{ printf("KW_LAZY: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "fsharp_lexer.l"
{ printf("KW_LET: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 105 "fsharp_lexer.l"
{ printf("KW_MATCH: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 106 "fsharp_lexer.l"
{ printf("KW_MEMBER: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 107 "fsharp_lexer.l"
{ printf("KW_MODULE: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 108 "fsharp_lexer.l"
{ printf("KW_MUTABLE: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 109 "fsharp_lexer.l"
{ printf("KW_NAMESPACE: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 110 "fsharp_lexer.l"
{ printf("KW_NEW: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "fsharp_lexer.l"
{ printf("KW_NULL: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "fsharp_lexer.l"
{ printf("KW_OF: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "fsharp_lexer.l"
{ printf("KW_OPEN: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "fsharp_lexer.l"
{ printf("KW_OR: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "fsharp_lexer.l"
{ printf("KW_OVERRIDE: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "fsharp_lexer.l"
{ printf("KW_PRIVATE: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "fsharp_lexer.l"
{ printf("KW_PUBLIC: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "fsharp_lexer.l"
{ printf("KW_REC: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "fsharp_lexer.l"
{ printf("KW_RETURN: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "fsharp_lexer.l"
{ printf("KW_RETURN_BANG: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 121 "fsharp_lexer.l"
{ printf("KW_SELECT: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 122 "fsharp_lexer.l"
{ printf("KW_STATIC: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "fsharp_lexer.l"
{ printf("KW_STRUCT: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "fsharp_lexer.l"
{ printf("KW_THEN: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "fsharp_lexer.l"
{ printf("KW_TO: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "fsharp_lexer.l"
{ printf("KW_TRY: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "fsharp_lexer.l"
{ printf("KW_TYPE: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "fsharp_lexer.l"
{ printf("KW_UPCAST: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 129 "fsharp_lexer.l"
{ printf("KW_USE: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 130 "fsharp_lexer.l"
{ printf("KW_USE_BANG: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 131 "fsharp_lexer.l"
{ printf("KW_VAL: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 132 "fsharp_lexer.l"
{ printf("KW_VOID: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 133 "fsharp_lexer.l"
{ printf("KW_WHEN: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 134 "fsharp_lexer.l"
{ printf("KW_WHILE: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 135 "fsharp_lexer.l"
{ printf("KW_WITH: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 136 "fsharp_lexer.l"
{ printf("KW_YIELD: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 137 "fsharp_lexer.l"
{ printf("KW_YIELD_BANG: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "fsharp_lexer.l"
{ printf("BOOL_TRUE: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 "fsharp_lexer.l"
{ printf("BOOL_FALSE: %s\n", yytext); }
	YY_BREAK
/* ----- идентификаторы ----- */
case 68:
YY_RULE_SETUP
#line 144 "fsharp_lexer.l"
{ printf("WILDCARD\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 145 "fsharp_lexer.l"
{
    int offset = 0;
    bool valid = true;
    while (offset < yyleng) {
        bool first = offset == 0;
        UChar32 cp;
        U8_NEXT(yytext, offset, yyleng, cp);
        int category = cp < 0 ? U_UNASSIGNED : u_charType(cp);
        bool letter = (category >= U_UPPERCASE_LETTER && category <= U_OTHER_LETTER) ||
                      category == U_LETTER_NUMBER;
        bool continuation = (cp >= '0' && cp <= '9') || cp == '\'' ||
                            category == U_CONNECTOR_PUNCTUATION ||
                            category == U_NON_SPACING_MARK ||
                            category == U_COMBINING_SPACING_MARK ||
                            category == U_FORMAT_CHAR;
        if (cp < 0 || (!letter && cp != '_' && (first || !continuation))) {
            valid = false;
            break;
        }
    }
    if (valid) {
        printf("IDENTIFIER: %s\n", yytext);
    } else {
        fprintf(stderr, "ERROR at line %d: invalid identifier: %s\n", yylineno, yytext);
        hadError = true;
    }
}
	YY_BREAK
/* ----- операторы ----- */
case 70:
YY_RULE_SETUP
#line 175 "fsharp_lexer.l"
{ printf("OP_PLUS\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 176 "fsharp_lexer.l"
{ printf("OP_MINUS\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 177 "fsharp_lexer.l"
{ printf("OP_MUL\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 178 "fsharp_lexer.l"
{ printf("OP_DIV\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 179 "fsharp_lexer.l"
{ printf("OP_MOD\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 180 "fsharp_lexer.l"
{ printf("OP_EQUAL_OR_EQUALS_SIGN\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 181 "fsharp_lexer.l"
{ printf("OP_NOT_EQUAL\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 182 "fsharp_lexer.l"
{ printf("OP_LT\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 183 "fsharp_lexer.l"
{ printf("OP_LE\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 184 "fsharp_lexer.l"
{ printf("OP_GT\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 185 "fsharp_lexer.l"
{ printf("OP_GE\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 186 "fsharp_lexer.l"
{ printf("OP_ASSIGN\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 187 "fsharp_lexer.l"
{ printf("OP_BOOL_AND\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 188 "fsharp_lexer.l"
{ printf("OP_BOOL_OR\n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 189 "fsharp_lexer.l"
{ printf("OP_CONS\n"); }
	YY_BREAK
/* ----- синтаксические знаки ----- */
case 85:
YY_RULE_SETUP
#line 193 "fsharp_lexer.l"
{
    ++braceStack.back();
    printf("LBRACE\n");
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 197 "fsharp_lexer.l"
{
    if (braceStack.back() == 0) {
        braceStack.pop_back();
        yy_pop_state();
        printf("INTERP_EXPR_END\n");
    } else {
        --braceStack.back();
        printf("RBRACE\n");
    }
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 208 "fsharp_lexer.l"
{ printf("ARROW\n"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 209 "fsharp_lexer.l"
{ printf("DOT\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 210 "fsharp_lexer.l"
{ printf("RANGE\n"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 211 "fsharp_lexer.l"
{ printf("COLON\n"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 212 "fsharp_lexer.l"
{ printf("LPAREN\n"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 213 "fsharp_lexer.l"
{ printf("RPAREN\n"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 214 "fsharp_lexer.l"
{ printf("LBRACKET\n"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 215 "fsharp_lexer.l"
{ printf("RBRACKET\n"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 216 "fsharp_lexer.l"
{ printf("ARRAY_START\n"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 217 "fsharp_lexer.l"
{ printf("ARRAY_END\n"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 218 "fsharp_lexer.l"
{ printf("LBRACE\n"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 219 "fsharp_lexer.l"
{ printf("RBRACE\n"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 220 "fsharp_lexer.l"
{ printf("COMMA\n"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 221 "fsharp_lexer.l"
{ printf("SEMICOLON\n"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 222 "fsharp_lexer.l"
{ printf("BAR\n"); }
	YY_BREAK
/* ----- числа ----- */
/* Первая точка диапазона не входит в вещественный литерал. */
case 102:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 227 "fsharp_lexer.l"
{ convert_to_decimal(yytext, 10); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 228 "fsharp_lexer.l"
{ convert_to_float(yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 229 "fsharp_lexer.l"
{ convert_to_float(yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 230 "fsharp_lexer.l"
{
    int base = 10;
    if (yytext[0] == '0') {
        switch (yytext[1]) {
            case 'x': case 'X': base = 16; break;
            case 'o': case 'O': base = 8; break;
            case 'b': case 'B': base = 2; break;
        }
    }
    convert_to_decimal(yytext, base);
}
	YY_BREAK
case 106:
#line 242 "fsharp_lexer.l"
case 107:
YY_RULE_SETUP
#line 242 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: invalid numeric literal: %s\n", yylineno, yytext);
    hadError = true;
}
	YY_BREAK
/* ----- символьные литералы ----- */
case 108:
YY_RULE_SETUP
#line 249 "fsharp_lexer.l"
{
    int offset = 1;
    int count = 0;
    UChar32 cp = 0;
    bool valid = true;
    while (offset < yyleng - 1) {
        if (yytext[offset] == '\\') {
            std::string value;
            parse_string_escape(value, yytext[offset + 1]);
            cp = static_cast<unsigned char>(value[0]);
            offset += 2;
        } else {
            U8_NEXT(yytext, offset, yyleng - 1, cp);
            if (cp < 0 || cp > 0xffff)
                valid = false;
        }
        ++count;
    }
    if (!valid || count != 1) {
        fprintf(stderr, "ERROR at line %d: character literal must contain one UTF-16 code unit\n", yylineno);
        hadError = true;
    } else {
        std::string value;
        parse_unicode(value, cp);
        std::cout << "CHAR_LITERAL: " << value << std::endl;
    }
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 276 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: invalid or unterminated character literal\n", yylineno);
    hadError = true;
}
	YY_BREAK
/* ----- комментарии ----- */
case 110:
YY_RULE_SETUP
#line 283 "fsharp_lexer.l"
{ /* Пропускаем комментарий, оставляя перевод строки для отдельного правила. */ }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 284 "fsharp_lexer.l"
{
    commentDepth = 1;
    yy_push_state(MULTILINE_COMMENT);
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 288 "fsharp_lexer.l"
{ ++commentDepth; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 289 "fsharp_lexer.l"
{
    if (--commentDepth == 0)
        yy_pop_state();
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 293 "fsharp_lexer.l"
{ /* Содержимое комментария. */ }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 294 "fsharp_lexer.l"
{ /* Содержимое комментария. */ }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 295 "fsharp_lexer.l"
{
    if (yyleng == 1 && yytext[0] == '\r')
        ++yylineno;
    printf("NEWLINE\n");
}
	YY_BREAK
/* ----- обычные строки ----- */
/* Разделители комментариев внутри строк не меняют глубину вложенности. */
case 117:
YY_RULE_SETUP
#line 304 "fsharp_lexer.l"
{
    stringBuffer.clear();
    yy_push_state(STRING);
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 308 "fsharp_lexer.l"
{
    yy_pop_state();
    if (commentDepth == 0)
        std::cout << "STRING_LITERAL: " << stringBuffer << std::endl;
}
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 313 "fsharp_lexer.l"
{
    int offset = 0;
    bool valid = true;
    while (offset < yyleng) {
        UChar32 cp;
        U8_NEXT(yytext, offset, yyleng, cp);
        if (cp < 0)
            valid = false;
    }
    for (int i = 0; i < yyleng; ++i) {
        if (yytext[i] == '\r' && (i + 1 == yyleng || yytext[i + 1] != '\n'))
            ++yylineno;
    }
    if (valid) {
        stringBuffer.append(yytext, yyleng);
    } else {
        fprintf(stderr, "ERROR at line %d: invalid UTF-8 in string\n", yylineno);
        hadError = true;
    }
}
	YY_BREAK
/* ----- интерполированные строки ----- */
case 120:
YY_RULE_SETUP
#line 336 "fsharp_lexer.l"
{
    yy_push_state(INTERPOLATED_STRING);
    printf("INTERP_START\n");
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 340 "fsharp_lexer.l"
{ printf("INTERP_TEXT: %c\n", yytext[0]); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 341 "fsharp_lexer.l"
{
    braceStack.push_back(0);
    yy_push_state(INTERPOLATION_EXPR);
    printf("INTERP_EXPR_START\n");
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 346 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: unmatched closing brace in interpolated string\n", yylineno);
    hadError = true;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 350 "fsharp_lexer.l"
{
    yy_pop_state();
    printf("INTERP_END\n");
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 354 "fsharp_lexer.l"
{ printf("INTERP_TEXT: %s\n", yytext); }
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 355 "fsharp_lexer.l"
{
    if (yyleng == 1 && yytext[0] == '\r')
        ++yylineno;
    printf("INTERP_TEXT: %s\n", yytext);
}
	YY_BREAK
/* ----- escape-последовательности ----- */
case 127:
/* rule 127 can match eol */
YY_RULE_SETUP
#line 363 "fsharp_lexer.l"
{
    if (yytext[1] == '\r' && yytext[2] != '\n')
        ++yylineno;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 367 "fsharp_lexer.l"
{ parse_string_escape(stringBuffer, yytext[1]); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 368 "fsharp_lexer.l"
{ parse_template_escape(yytext[1]); }
	YY_BREAK
case 130:
#line 370 "fsharp_lexer.l"
case 131:
YY_RULE_SETUP
#line 370 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: invalid escape sequence: %s\n", yylineno, yytext);
    hadError = true;
}
	YY_BREAK
/* ----- пробельные символы, перевод строки и конец ввода ----- */
case 132:
YY_RULE_SETUP
#line 377 "fsharp_lexer.l"
{ /* Пробельные символы. */ }
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 378 "fsharp_lexer.l"
{
    if (yyleng == 1 && yytext[0] == '\r')
        ++yylineno;
    printf("NEWLINE\n");
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 383 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: unexpected character: %s\n", yylineno, yytext);
    hadError = true;
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 387 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: '*)' expected\n", yylineno);
    hadError = true;
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(INTERPOLATED_STRING):
#line 392 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: unterminated string literal\n", yylineno);
    hadError = true;
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION_EXPR):
#line 397 "fsharp_lexer.l"
{
    fprintf(stderr, "ERROR at line %d: unterminated interpolation expression\n", yylineno);
    hadError = true;
    yyterminate();
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 403 "fsharp_lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2020 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 412 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 412 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 411);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 403 "fsharp_lexer.l"


/* ----- преобразование чисел ----- */

void strip_underscores(const char* src, char* out, size_t cap)
{
    if (cap == 0)
        return;
    size_t w = 0;
    for (size_t r = 0; src[r] && w + 1 < cap; ++r) {
        if (src[r] != '_')
            out[w++] = src[r];
    }
    out[w] = '\0';
}

void convert_to_decimal(const char* src, int base)
{
    std::vector<char> buf(strlen(src) + 1);
    strip_underscores(src, buf.data(), buf.size());

    /* Большие целые числа не ограничены диапазоном машинного целого типа. */
    if (buf[strlen(buf.data()) - 1] == 'I') {
        printf("INT_LITERAL: %s\n", buf.data());
        return;
    }

    const char* digits = buf.data() + (base == 10 ? 0 : 2);
    char* suffix;
    errno = 0;
    unsigned long long value = strtoull(digits, &suffix, base);
    if (errno == ERANGE) {
        fprintf(stderr, "ERROR at line %d: integer overflow: %s\n", yylineno, src);
        hadError = true;
    } else {
        /* Сохраняем суффикс для последующей проверки типа. */
        printf("INT_LITERAL: %llu%s\n", value, suffix);
    }
}

void convert_to_float(const char* src)
{
    std::vector<char> buf(strlen(src) + 1);
    strip_underscores(src, buf.data(), buf.size());
    size_t length = strlen(buf.data());
    char suffix = buf[length - 1];

    /* Литералы decimal не должны терять точность при преобразовании в double. */
    if (suffix == 'm' || suffix == 'M') {
        printf("DECIMAL_LITERAL: %s\n", buf.data());
        return;
    }

    bool single = suffix == 'f' || suffix == 'F';
    if (single)
        buf[length - 1] = '\0';
    errno = 0;
    double value = single ? strtof(buf.data(), NULL) : strtod(buf.data(), NULL);
    if (errno == ERANGE) {
        fprintf(stderr, "ERROR at line %d: floating-point value out of range: %s\n", yylineno, src);
        hadError = true;
    } else {
        printf("%s: %.*g\n", single ? "FLOAT32_LITERAL" : "FLOAT64_LITERAL",
               single ? 9 : 17, value);
    }
}

/* ----- Unicode и escape-последовательности ----- */

void parse_unicode(std::string& buf, long cp)
{
    if (cp < 0 || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) {
        fprintf(stderr, "ERROR at line %d: Unicode code point is out of range\n", yylineno);
        hadError = true;
        return;
    }

    char text[4];
    int length = 0;
    U8_APPEND_UNSAFE(text, length, cp);
    buf.append(text, length);
}

void parse_string_escape(std::string& buf, char c)
{
    switch (c) {
        case 'n': buf += '\n'; break;
        case 't': buf += '\t'; break;
        case 'v': buf += '\v'; break;
        case '\\': case '"': case '\'': buf += c; break;
        default:
            fprintf(stderr, "ERROR at line %d: invalid escape sequence: \\%c\n", yylineno, c);
            hadError = true;
    }
}

void parse_template_escape(char c)
{
    std::string value;
    parse_string_escape(value, c);
    if (!value.empty())
        std::cout << "INTERP_TEXT: " << value << std::endl;
}

int main(int argc, char* argv[])
{
    if (argc > 2) {
        fprintf(stderr, "Usage: %s [input_file]\n", argv[0]);
        return 1;
    }

    if (argc == 2) {
        if (fopen_s(&yyin, argv[1], "rb") != 0) {
            perror("fopen_s");
            return 1;
        }
    }

    yylex();

    if (argc == 2)
        fclose(yyin);
    yylex_destroy();
    return hadError ? 1 : 0;
}

